FROM python:3.11-slim-bookworm

# Instala dependências do sistema + repositório oficial da Raspberry Pi Foundation
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 libglib2.0-0 libgomp1 curl gnupg ca-certificates && \
    curl -fsSL https://archive.raspberrypi.com/debian/raspberrypi.gpg.key \
    | gpg --dearmor -o /usr/share/keyrings/raspberrypi-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] https://archive.raspberrypi.com/debian/ bookworm main" \
    > /etc/apt/sources.list.d/raspi.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends rpicam-apps-lite && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Cache de camadas para dependências Python
COPY app/requirements.txt .

# Alteração da Aula 3: PyTorch CPU-only
RUN pip install --no-cache-dir torch torchvision \
    --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir -r requirements.txt

# Copia código da aplicação
COPY app/ .

EXPOSE 8000

# Copia módulo de pré-processamento
COPY preprocessing/ ./preprocessing/
# Executa o Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
